nome = str(input('Digite seu nome completo: ')).strip().lower().upper()
n = nome.split()
print('Prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu ultimo nome é {}'.format(n[len(n)-1]))
